<<<
== Prerequisites

Set up a vSnap server by deploying a virtual appliance or running the installer on a custom Linux system. For simplicity and ease of deployment, using the virtual appliance is highly recommended.

Detailed instructions for installing, configuring, and managing a vSnap server can be found https://www.ibm.com/support/knowledgecenter/en/SSNQFQ_10.1.5/spp/t_spp_install_vsnap.html[here].

The key steps required for configuring the vSnap server for the purpose of the validation tests are summarized below.

=== Initial deployment

* Deploy the vSnap OVA in a VMware environment using the `Deploy OVF Template` option.
* Enter network properties for the virtual machine as part of the deployment wizard, or leave them blank to use DHCP. You can also set the network properties later once the virtual machine is up and running.
* Once deployment completes, power on the system and login using the default credentials:
** Username: `serveradmin`
** Password: `sppDP758-SysXyz`
* Upon initial login, you are prompted to change the default password. Enter the default password first, then enter the new password twice. You may be forced to log out and log back in after changing the password.
* If you did not previously configure the network properties, you can do so now by running `sudo nmtui` or by other means if you are already familiar with Linux administration.

NOTE: The `serveradmin` user has `sudo` privileges.

=== Configuring storage

For the purpose of running the validation tests you must configure two storage areas:

* The primary disk-based storage pool where data is initially written.
* A disk-based cache area where data is temporarily staged while it is being offloaded/copied from the primary storage pool to the object storage.

*Primary storage pool*

By default, the vSnap virtual appliance includes an unused 100 GB SCSI disk which can be used to create the storage pool. If you plan to run basic tests to verify functionality and/or measure performance using a data set that is smaller than 100 GB, it is sufficient to use the default disk to create the storage pool. If you plan to test with larger data sets, you may want to attach additional disks to create a larger storage pool.

Run `vsnap disk show` to list disks and confirm that one or more unused disks are available. Sample output:

----
[serveradmin@vsnap-vadp ~]$ vsnap disk show
UUID                             | TYPE | VENDOR | MODEL        | SIZE     | USED AS     | KNAME | NAME
-----------------------------------------------------------------------------------------------------------
6000c299371bdcb647c80720602079bc | SCSI | VMware | Virtual disk | 70.00GB  | LVM2_member | sda   | /dev/sda
6000c29b8ea25349e3a884d58f72e640 | SCSI | VMware | Virtual disk | 100.00GB | unused      | sdb   | /dev/sdb
6000c297cb8078cf9f56ab688a326a24 | SCSI | VMware | Virtual disk | 128.00GB | LVM2_member | sdc   | /dev/sdc
----

To use a storage pool larger than 100 GB, attach one or more additional disks to the system, run `vsnap disk rescan` and then rerun `vsnap disk show` to confirm that they are all recognized as being unused.

To create a storage pool using all available unused disks, run `vsnap system init`. Afterwards, run `vsnap pool show` to confirm that a storage pool has been created.

*Cache area*

TODO

=== Setting up the validation test scripts



* The test scripts will be run locally on a vSnap. To deploy and initialize a vSnap use the following link:



** Install vSnap: https://www.ibm.com/support/knowledgecenter/en/SSNQFQ_10.1.5/spp/t_spp_install_vsnap.html[install]



** Initialize vSnap: https://www.ibm.com/support/knowledgecenter/en/SSNQFQ_10.1.5/spp/t_spp_config_vsnap_initialize.html[initialize]



** Expand vSnap pool (if needed): https://www.ibm.com/support/knowledgecenter/en/SSNQFQ_10.1.5/spp/t_spp_expand_storage_pool.html[expand_pool]

* Install git on the vSnap to clone the s3validator repo. Running the following commands on the vSnap will give you access to
the test scripts locally on your freshly deployed vSnap.

[source, bash]
----
$ sudo apt-get install git

$ git clone https://github.com/sppautomation/s3validator.git
----


* install environment to run the scripts.
**  Run the script "install.sh" that is in the s3validator directory.
** This will set up a Python virtual environment and will install some
dependencies that are necessary to run tests. Note that packages will
be installed into the newly created virtual environment so no changes
will be made to host's software.

[source, bash]
----
$ ./install.sh
----



