<<<
== Configuration

The test scripts are divided into three categories as follows:

. Functional - These tests will run offload and restore using the registered s3 provider
. Performance - This test will tell us the throughput for a base offload and restore
. Scale - This test allows us to measure performance of the vSnap by varying the number of offloads it handles concurrently

=== Configuring S3 Provider

* To run tests, you need to first provide the details of the S3
provider. To do this, edit the following file:

    tests/config/cloud_endpoint.json

and provide the following information:

* endpoint ->  URL of the S3 provider.
* api_key -> Access key to be used to login.
* api_secret -> Password for the key provided above.
* bucket -> Bucket name.
* provider ->  You can use the default value.

=== Test Configuration

In directory tests update the pytest.ini file to set the offload size in MB's. Following are the fields you can configure, the default values are
mentioned for reference.

* Total time out (10800 seconds)

* Functional
** Base offload (10 MB)
** Incremental offload (5 MB)
** Number of increments (3)


* Performance
** Base offload size (1000 MB)

* Scale
** Base offload Size (10 MB)
** Number of offloads (10)
** Max vsnap streams (3)

