= S3 Object Storage Provider Validation
for IBM Spectrum Protect Plus
:doctype: book
:toc: left
:toclevels: 2
:icons: font
:pagenums:
:sectnums:
:pdf-page-size: letter
:source-highlighter: highlight.js

NOTE: Copyright 2019 IBM Corp. All rights reserved. The contents of this document and any attachments are strictly confidential and are supplied on the understanding that they will be held confidentially and not disclosed to third parties without the prior written consent of IBM.

<<<

== Introduction

This document describes the automated functional and performance tests that enable you to validate that a cloud object storage provider is compatible with IBM Spectrum Protect Plus.

Running these tests will verify that IBM Spectrum Protect Plus can successfully copy data to and restore from an S3-compatible object storage provider. The tests will also enable you to measure performance and analyze how well the solution scales.

IBM Spectrum Protect Plus (SPP) works by writing data to disk-based storage called vSnap servers which serve as the primary backup destination. Data in vSnap servers can then be copied to S3-compatible object storage providers using an incremental-forever approach.

A typical deployment consists of one SPP server which acts as the control plane, and one or more vSnap servers which store data.

SPP is distributed as a pre-built virtual appliance that can be deployed in VMware or Hyper-V environments. vSnap can be similarly deployed as a pre-built virtual appliance, or it can be installed on a custom physical or virtual Linux system that meets certain pre-requisites.

In order to run the validation tests, an SPP server is not required, but you must at least install and configure a vSnap server, as described in the `Prerequisites` section.

The validation tests are distributed as a `tar.gz` archive consisting of a Python-based test suite and associated configuration files. The tests are designed to run locally on a vSnap server. They work by generating a random set of data, writing it to the vSnap server's disk-based storage pool, and then copying the data to the object storage. The tests also restore data by downloading it from object storage and verifying that its contents are valid.

<<<

== Prerequisites

Set up a vSnap server by deploying the virtual appliance in a VMware vSphere environment.

Detailed instructions for installing, configuring, and managing a vSnap server can be found in https://www.ibm.com/support/knowledgecenter/en/SSNQFQ_10.1.5/spp/t_spp_install_vsnap.html[IBM Knowledge Center].

The key steps required for configuring the vSnap server for the purpose of the validation tests are summarized below.

=== Deploy the vSnap virtual appliance

* Deploy the vSnap OVA in a VMware vSphere environment using the `Deploy OVF Template` option.
* Enter network properties for the virtual machine as part of the deployment wizard or leave them blank to use DHCP. You can also configure the network properties at a later time once the virtual machine is up and running.
* Once deployment completes, before powering on the virtual machine, edit its settings to adjust the virtual hardware. For a system intended for the validation tests, specify the following configuration:
** Number of vCPUs: 8
** Total Memory: 40 GB
** Number of network adapters: 1
*** Using a 10 Gbit network adapter is recommended.
* Power on the virtual machine and login using the default credentials:
** Username: `serveradmin`
** Password: `sppDP758-SysXyz`
* Upon initial login, you are prompted to change the default password. Enter the default password first, then enter the new password twice. Upon changing the password, you are immediately logged out and must log back in using the new password.

NOTE: The `serveradmin` user has `sudo` privileges.

=== Configure network settings

If you did not previously configure the network properties during the OVA deployment wizard, you can do so by running `sudo nmtui` while logged in as the `serveradmin` user.

NOTE: Internet access is required in order to download updates and dependencies for the test suite.

=== Configure storage

The validation tests make use of two storage areas on the vSnap server:

* The primary disk-based storage pool where data is initially written. A storage pool of at least 500 GB is required for the validation tests.
* A disk-based cache area where data is temporarily staged while it is being copied from the primary storage pool to the object storage. A cache area of at least 128 GB is required for the validation tests.

*Primary storage pool*

The primary storage pool is the data repository where backup data is written. On a freshly installation of vSnap, no storage pool exists. As part of the vSnap initialization process, the pool is created using one or more SCSI disks.

By default, the vSnap virtual appliance includes an unused 100 GB SCSI disk which can be used to create the storage pool. You must attach additional disks to the virtual machine in order to create a pool that is 500 GB or larger.

To create the storage pool:

* Run `vsnap disk show` to list disks and confirm that one or more unused SCSI disks are available. By default, the vSnap virtual appliance includes an unused 100 GB SCSI disk (`/dev/sdb`) as seen in the sample output below:

----
[serveradmin@vsnap ~]$ vsnap disk show
UUID                             | TYPE | VENDOR | MODEL        | SIZE     | USED AS     | KNAME | NAME
-----------------------------------------------------------------------------------------------------------
6000c29c116da8f495b2039fcd7fa3c3 | SCSI | VMware | Virtual disk | 70.00GB  | LVM2_member | sda   | /dev/sda
6000c293f48c897ded5c3b50afb7ca28 | SCSI | VMware | Virtual disk | 100.00GB | unused      | sdb   | /dev/sdb
6000c294c22b7968054789932dcf6621 | SCSI | VMware | Virtual disk | 128.00GB | LVM2_member | sdc   | /dev/sdc
----

* Attach one or more additional disks to the system totaling at least 500 GB.
* Run `vsnap disk rescan` and then rerun `vsnap disk show` to confirm that the newly added disks are all recognized as being unused.
* Run `vsnap system init` to initialize the vSnap installation. As part of the initialization process, vSnap creates a storage pool using all available unused disks.
* When initialization completes, run `vsnap pool show` to confirm that a storage pool has been created. Note that a freshly created pool will show a few GB of space as being used. This is reserved for internal pool metadata. The rest of the space is listed as free. Sample output:

----
[serveradmin@vsnap ~]$ vsnap pool show
TOTAL: 1

ID: 1
NAME: primary
POOL TYPE: raid0
STATUS: ONLINE
HEALTH: 100
COMPRESSION: Yes
COMPRESSION RATIO: 1.00
DEDUPLICATION: No
DEDUPLICATION RATIO: 1.00
ENCRYPTION:
    ENABLED: No

TOTAL SPACE: 600.00GB
FREE SPACE: 590.00GB
USED SPACE: 10.00GB
DATA SIZE BEFORE DEDUPLICATION: 134.50KB
DATA SIZE BEFORE COMPRESSION: 53.50KB
CREATED: 2020-01-06 20:19:33 UTC
UPDATED: 2020-01-06 20:19:33 UTC
DISKS PER RAID GROUP: 1
DISKS IN POOL:
    RAID0:
        /dev/sdb1
        /dev/sdd1
----

*Cache area*

By default, the vSnap virtual appliance includes a 128 GB XFS filesystem mounted at `/opt/vsnap-data` which is used as the cache area. This is sufficient for the validation tests and no further manual configuration is required.

<<<

== Installation

=== Download and install the test suite

* Login to the vSnap server as the `serveradmin` user.
* Run the following command to install the most up-to-date SSL certificates.

----
sudo yum --enablerepo=base,updates reinstall ca-certificates
----

* The test suite is distributed as a `tar.gz` archive. Download the archive to the vSnap server, copy it to a suitable directory (e.g. `/home/serveradmin/`) and extract it using the command. The contents of the archive are extracted to a directory named `s3validator-<version>`.

----
tar -xzvf <filename>
----

* Invoke the installation script using the command:

----
s3validator-<version>/install.sh
----

The installation script creates a Python virtual environment in a new directory named `s3validator_venv` under the same parent directory where the archive was extracted. If an existing `s3validator_env` directory is found, the installer removes it and creates a new one. The installer then downloads and installs some dependencies in the virtual environment.

Sample output:

----
Creating virtual environment under: /home/serveradmin/s3validator_venv
Installing dependencies

[Output truncated]

Installation complete
----

Once the installation is complete, you are ready to configure and run the validation tests.

<<<

== Usage

=== Overview

The test suite consists of the following categories of tests.

*Functional test*

This test evaluates the basic functionality of copying data to object storage.

The test uploads data to the S3 endpoint in multiple iterations starting with a larger base copy followed by a few smaller incremental copies. The test also verifies downloads by restoring the data from each iteration.

Since this test is designed to validate basic functionality, by default it is configured to transfer a relatively small amount of data.

*Performance test*

This test evaluates the performance of the copy to object storage.

The test performs a single upload session to the S3 endpoint and measures the write throughput. It also verifies downloads by restoring the data and measuring the read throughput.

Since the goal of this test is to measure throughput, by default it is configured to transfer a larger amount of data compared to the functional test.

*Scale test*

This test evaluates the performance and scalability of the copy to object storage by driving multiple concurrent copy operations.

The test performs multiple uploads sessions to the S3 endpoint concurrently and measures the average write throughput.

=== Configure the test suite

* As the `serveradmin` user, run the command `vsnap user create` to create a new vSnap API user. Specify a new username and password when prompted.

Sample output:

----
[serveradmin@vsnap ~]$ vsnap user create
Username: testuser
Password: <not displayed>
Repeat for confirmation: <not displayed>

UID: 1003
GID: 1003
NAME: testuser
ROLE: vsnap_admin
----

* Modify the file `s3validator-<version>/tests/pytest.ini`. Under the `[pytest]` section of the configuration file, update the `username` and `password` values to specify the credentials of the newly created user.
* To configure the endpoint details, modify the file `s3validator-<version>/tests/config/cloud_endpoint.json` and set the appropriate values as described below.

Fields in `cloud_endpoint.json`:

[cols="30%a,70%a", options="header"]
|====
|Field|Description
|`endpoint`|Specify the endpoint URL to be used for the tests. The URL must include the prefix `http://` or `https://`. For example: `https://s3.amazonaws.com`.
|`api_key`|Specify the Access Key for the endpoint.
|`api_secret`|Specify the Secret Key for the endpoint.
|`bucket`|Specify the name of the bucket that will be used for the tests.
|`provider`|Do not edit this value. It must be set to `generic`.
|====

=== Run the test suite

* To invoke the functional tests, run:

----
s3validator-<version>/runtests.sh functional
----

* To invoke the performance tests, run:

----
s3validator-<version>/runtests.sh performance
----

* To invoke the scale tests, run:

----
s3validator-<version>/runtests.sh scale
----

NOTE: Depending on the type of the test and the data sizes involved, the commands above may take a long time to complete, ranging from several minutes to several hours. If a test doesn't complete within a default timeout period of 24 hours, the test is aborted.

Each time the test suite is invoked, its output is captured in a directory named `s3validator_logs_<timestamp>` under the same parent directory where the `s3validator` archive was extracted.

For assistance with troubleshooting, collect a vSnap support bundle using the command `vsnap system logcollect` and provide it to IBM along with the `s3validator_logs_<timestamp>` directory associated with the test run.

== Appendix

=== Configure optional test parameters

You can optionally modify test configuration parameters that dictate the data sizes and concurrency settings used for the functional, performance, and scale tests. The default values are sufficient for most purposes, but if needed, they can be modified by editing the file:

----
s3validator-<version>/tests/pytest.ini
----

*Functional test parameters*

Modify the values under the `[functional_test]` section of `pytest.ini`.

[cols="30%a,70%a", options="header"]
|====
|Field|Description
|`incr_count`|Specify the number of incremental copies that the test will perform after the initial base copy.
|`base_file_size_MB`|Specify the size (in MB) of the sample data set that will be generated for the initial base copy.
|`incr_file_size_MB`|Specify the size (in MB) of the same data set that will generated for each incremental copy.
|====

*Performance test parameters*

Modify the values under the `[performance_test]` section of `pytest.ini`.

[cols="30%a,70%a", options="header"]
|====
|Field|Description
|`base_file_size_MB`|Specify the size (in MB) of the sample data set that will be generated for the base copy used to evaluate upload throughput.
|====

*Scale test parameters*

Modify the values under the `[scale_test]` section of `pytest.ini`.

[cols="30%a,70%a", options="header"]
|====
|Field|Description
|`base_file_size_MB`|Specify the size (in MB) of the sample data set that will be generated for *each* base copy as part of the scale test.
|`num_of_sessions`|Specify the total number of copies that will be triggered as part of the scale test.
|`max_parallel_sessions`|Specify the maximum number of copies that will be processed in parallel.

For example, if `max_parallel_sessions` is set to `5`, this means that the vSnap server will maintain a pool of at most 5 workers that are available to perform copy sessions. If `num_of_sessions` is set to `10` this means that the scale test will create 10 data sets (each of size `base_file_size_MB`) and then attempt to upload all of them. The first 5 will begin immediately as there are 5 workers available, while the remaining 5 sessions will wait in a queue. As each worker in the pool finishes its session, it will pick up the next pending session in the queue, until there are none left. At the end, the test suite evaluates the average throughput of each copy session.

You can perform multiple test runs with different versions of `max_parallel_sessions` to evaluate how the average performance scales as the number of workers increases or decreases.

Note that increasing the number of workers causes CPU, memory, and network usage to increase as well. The default value of `5` is what most vSnap servers in production run with.
|====

=== Expand the primary storage pool

If you configure the optional test parameters to define data sizes larger than the default values, you may need to expand the storage pool to ensure it is large enough to store the data sets.

To expand the storage pool:

* Run `vsnap pool show` and make a note of the pool ID. Typically this is `1` but it may differ.
* Attach one or more new SCSI disks to the vSnap virtual machine.
* Run `vsnap disk rescan` and then run `vsnap disk show` to confirm that the newly added disks are all recognized as being unused.
* Run `vsnap pool expand --id <ID>` (replace `<ID>` with the appropriate pool ID). This command detects all unused SCSI disks and adds them to the existing storage pool.
* Run `vsnap pool show` to confirm that the expanded size is accurately reflected.

=== Expand the cache area

For a primary storage pool smaller than 10 TB, the default cache area of 128 GB is sufficient. If you expand the primary storage pool to be larger than 10 TB, you must also expand the cache area to a total size of 500 GB or higher.

The `/opt/vsnap-data` filesystem sits on an LVM logical volume named `vsnapdatalv` within a volume group named `vsnapdata`.

To expand the cache area:

* Attach a SCSI disk to the system, run `vsnap disk rescan` and then rerun `vsnap disk show` to confirm that they are all recognized as being unused. The sample commands below assume that the newly added disk is named `/dev/sdx`.
* Create a PV on the disk using command: `sudo pvcreate /dev/sdx`
* Extend the existing VG using command: `sudo vgextend vsnapdata /dev/sdx`
* Extend the existing LV using command: `sudo lvextend -l 100%VG /dev/mapper/vsnapdata-vsnapdatalv`
* Grow the XFS filesystem using command: `sudo xfs_growfs /dev/mapper/vsnapdata-vsnapdatalv`
* Finally, run `df -h` and verify that the volume `/opt/vsnap-data` is mounted and has the desired new size.

